import fs from 'node:fs';
let html=fs.readFileSync('source.html','utf8');
const match=html.match(/<script>\s*([\s\S]*?)<\/script>/);
if(!match)throw new Error('Application script missing');
let code=match[1];
html=html.replace(/<script[\s\S]*?<\/script>/g,'');
html=html.replace(/<link rel="manifest"[^>]+>/,'');
html=html.replace(/<section class="card no-print" style="border:2px solid #d97706">[\s\S]*?<\/section>/,'<section class="card no-print"><strong>Version de test mobile</strong><p class="muted">Les données sont synchronisées avec votre compte existant. Testez avec un profil dédié.</p></section>');
html=html.replaceAll('Suivi des heures','Suivi des heures Pro');
html=html.replace('Entre para sincronizar os dados entre iPhone e computador.','Connectez-vous pour retrouver vos données.');
html=html.replace('Seu e-mail','Votre adresse e-mail').replace('Enviar link de acesso','Recevoir un lien de connexion');
html=html.replaceAll('href="/privacy.html"','href="https://jefrisrenovation-netizen.github.io/privacy.html"');
html=html.replace('</body>','<footer class="no-print" style="padding:20px;text-align:center"><a href="https://jefrisrenovation-netizen.github.io/privacy.html" target="_blank" rel="noopener">Confidentialité</a> · <a href="mailto:jefrisrenovation@gmail.com">Assistance</a></footer><script type="module" src="/src/main.js"></script></body>');
html=html.replace('</style>','@media(max-width:600px){table{min-width:720px}.brand h1{font-size:20px}}button:disabled{opacity:.55}</style>');
code=code.replace('const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);','const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{detectSessionInUrl:false}});');
code=code.replace('Link enviado. Abra o e-mail, entre no site principal e depois volte a /preview/.','Lien envoyé. Ouvrez votre e-mail sur ce téléphone, puis revenez à l’application.');
code=code.replace('Digite seu e-mail.','Saisissez votre adresse e-mail.').replace('Enviando link...','Envoi du lien…');
const names=[...code.matchAll(/(?:async\s+)?function\s+(\w+)\(/g)].map(m=>m[1]);
fs.mkdirSync('src',{recursive:true});
const imports=`import {createClient} from '@supabase/supabase-js';\nimport {Capacitor} from '@capacitor/core';\nimport {App} from '@capacitor/app';\nimport {Filesystem,Directory} from '@capacitor/filesystem';\nimport {Share} from '@capacitor/share';\nimport {jsPDF} from 'jspdf';\nimport {autoTable} from 'jspdf-autotable';\nimport {authTokens,reportFilename} from './helpers.mjs';\n`;
const mobile=fs.readFileSync('scripts/mobile-runtime.js','utf8');
fs.writeFileSync('src/main.js',imports+code+'\n'+mobile+'\nObject.assign(window,{'+[...new Set(names.concat(['exportMobileReport','requestAccountDeletion']))].join(',')+'});\n');
fs.writeFileSync('index.html',html);
fs.mkdirSync('public/assets',{recursive:true});
fs.cpSync('../preview/assets','public/assets',{recursive:true});
console.log('Prepared packaged application with local dependencies.');
